In NumPy, when the dimension of matrix matches either column or row of the matrix, it performs operation with the corresponding columns (or rows). For example,

$A=\begin{bmatrix}
a_{11} & a_{12} & a_{13}\\
a_{21} & a_{22} & a_{23}
\end{bmatrix}$, $B=\begin{bmatrix}
b_{11} \\
b_{21} 
\end{bmatrix}$


$ A+B= \begin{bmatrix}
A_{1}+B & A_{2}+B & A_{3}+B
\end{bmatrix}$

Lets take a look at the below example:

In [76]:
import numpy as np
a = np.random.randn(2, 3)#.reshape((2,3))
b = np.arange(2).reshape((2,1)) 
c = a + b 
a,b,c

(array([[ 1.14942146, -1.18918251, -0.53028114],
        [-0.27223153, -0.62291622,  0.92609425]]),
 array([[0],
        [1]]),
 array([[ 1.14942146, -1.18918251, -0.53028114],
        [ 0.72776847,  0.37708378,  1.92609425]]))

Such property is quite useful generating matrices of interest. For example, let's say that we want to generate a matrix, 
$ B= \begin{bmatrix}
B_{1} & B_{2}&\cdots& B_{m}
\end{bmatrix}$ such that $B_{i}=\begin{bmatrix} i-1 \\ i \\ \vdots \\ i+n-1\end{bmatrix}$. 

We can simply start with a row identity matrix of column $m$, and mulitply it by column sequence matrix $\begin{bmatrix} 0\\1\\\vdots\\n-1\end{bmatrix}$, to get the following matrix $\begin{bmatrix}
B_{1} & B_{1}&\cdots& B_{1} \end{bmatrix} =\begin{bmatrix} 0 & 0 & \cdots & 0\\ 1 & 1 & \cdots & 1 \\ \vdots & & & \vdots \\  n-1 & n-1 & \cdots & n-1 \end{bmatrix}$. Then we add a row sequence matrix $\begin{bmatrix} 0& 1 & \cdots & m \end{bmatrix}$ to get $ B= \begin{bmatrix}
B_{1} & B_{2}&\cdots& B_{m}
\end{bmatrix}$. See the below example:

In [80]:
a = np.arange(12).reshape(4, 3)
b=np.ones(2)*np.arange(3).reshape(3,1)+np.arange(2).reshape(1,2)
a,b,a@b

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[0., 1.],
        [1., 2.],
        [2., 3.]]),
 array([[ 5.,  8.],
        [14., 26.],
        [23., 44.],
        [32., 62.]]))

In [45]:
#def 

array([[-0.32513332,  1.50175137,  1.87014817],
       [ 2.62916916,  2.09790145,  0.55520074]])

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[0., 1.],
        [1., 2.],
        [2., 3.]]),
 array([[ 5.,  8.],
        [14., 26.],
        [23., 44.],
        [32., 62.]]))

In [53]:
a.shape = (3,4); b.shape = (4,1);
for i in range(3): 
    for j in range(4): 
        c[i][j] = a[i][j] + b[j] 

In [43]:
a=(np.ones(12)+2).reshape((3,4))

In [44]:
b=np.array((1,2,3,4)).reshape((4,1))
c=np.zeros(12).reshape((3,4))

In [45]:
a.shape = (3,4); b.shape = (4,1);
for i in range(3): 
    for j in range(4): 
        c[i][j] = a[i][j] + b[j] 

In [51]:
a+b.T

array([[4., 5., 6., 7.],
       [4., 5., 6., 7.],
       [4., 5., 6., 7.]])