In [12]:
###
###
# how to do inner product between matrix with shape one dimension?
# ex ) np.array([0,0]) has shape (2,)
# but the dot proudct of this array with and array with shape (10,1) does not work
import pandas as pd
import numpy as np

df=pd.read_csv('../data/examPF.csv')
x=np.array(df[df.columns[0]])
X=np.column_stack((np.ones(12),x))
w0=np.array([0,0]).reshape((2,1))
A=X
X=w0

1. Creating a matrix in python. 
Linear system. Numpy array to matrix. using reshape((n,m)). For creating a matrix with n rows and m columns. 
One dimensional vector can be created as below, but normally in linear algebra one-dimensional vector is column vector, which has dimension of n by 1. In Numpy, typical one dimensional vector has single dimension, which is n.

In [30]:
v=np.ones(8)
len(v.shape)

1

The problem with this setting is that naturally occuring one-dimensional vector cannot be used in matrix operations. Take look at this example. 

In [48]:
v=np.ones(2);
w=np.arange(16).reshape((8,2));
ans=(w@v.T,
w@v.reshape((2,1)),
w@v)
print(ans)
(ans[0].shape,
 ans[1].shape,
 ans[2].shape
)

(array([ 1.,  5.,  9., 13., 17., 21., 25., 29.]), array([[ 1.],
       [ 5.],
       [ 9.],
       [13.],
       [17.],
       [21.],
       [25.],
       [29.]]), array([ 1.,  5.,  9., 13., 17., 21., 25., 29.]))


((8,), (8, 1), (8,))

One need to make it a vector with 2-dimensional length. How? The answer is "reshape". 

2. Operator
Matrix multiplications. Inner products. 

In [21]:
# Matrix multiplications.
print(A@X)
print("Dimensions of each matrix:")
A.shape, X.shape, (A@X).shape 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Dimensions of each matrix:


((12, 2), (2, 1), (12, 1))

## Inner products



In [24]:
np.dot(A,X) # matches

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [26]:
A@X

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

Read: 
https://stackoverflow.com/questions/22737000/one-dimensional-array-shapes-length-vs-length-1-vs-length