Jul 22, 2021. John Park


This notebook is a summary of theories and definitions of Prof. Gilbert Strang's book: "Linear Algebra and its applications".



#### Chap 1. Matrices and Gaussian Eliminations. Theorems and Definitions ###
1L. Inverse of $AB$. 
$$ (AB)^{-1}=B^{-1}A^{-1} $$

2L. Every nonsingular matrix is invertible.

3L. An n by n matrix is invertible iff it has n pivots.

4L. tanspose of $AB$.
$$ (AB)^{T}=B^{T}A^{T} $$

5L. Tanspose of $A^{-1}$.
$$ (A^{-1})^{T}=(A^{T})^{-1} $$

6L. For a given matrix $R$,
$$RR^{T}=R^{T}R$$

7L. Ill conditioned and well conditioned matrices. 

8L. If $A=A^{T}$, $A=LDU=LDL^{T}$.




1D. Definition of transpose.
$$(A_{ij})^{T}=A_{ji}$$

2D. A band matirx $A$ with $w$ has $a_{ij}=0 $ except the band $\abs{i-j}<w$.

3D. The matrix A is tridiagonal iff $w=1$.










#### Practice with Python NumPy.

In [32]:
##1 Defintions of matries; A, B, R. 
import numpy as np
from numpy.linalg import inv 
from numpy.linalg import det
from numpy import transpose as t
from numpy.random import rand as random

A=np.array((1,2,0,2,6,4,0,4,11)).reshape(3,3)
B=np.array((2,3,3,0,5,7,6,9,8)).reshape(3,3) 
print((A,B))

#test 4L
print(t(A@B),t(B)@t(A))

print(det(A@B),det(A),det(B))

#test 1L
print(inv(A@B),inv(B)@inv(A))
#det(A), det(B), det(A@B)



(array([[ 1,  2,  0],
       [ 2,  6,  4],
       [ 0,  4, 11]]), array([[2, 3, 3],
       [0, 5, 7],
       [6, 9, 8]]))
[[  2  28  66]
 [ 13  72 119]
 [ 17  80 116]] [[  2  28  66]
 [ 13  72 119]
 [ 17  80 116]]
-59.99999999999716 6.0 -9.999999999999993
[[ 19.46666667  -8.58333333   3.06666667]
 [-33.86666667  14.83333333  -5.26666667]
 [ 23.66666667 -10.33333333   3.66666667]] [[ 19.46666667  -8.58333333   3.06666667]
 [-33.86666667  14.83333333  -5.26666667]
 [ 23.66666667 -10.33333333   3.66666667]]


#### Chap 2. Vector Spaces. Theorems and Definitions. - The four fundamental Spaces

1D. Subspace.

Let $A$ is a $m$ by $n$ matrix.

#### 2-1. The Column Space of A. 

2A. The system $Ax=b$ is solvable iff $\exists k_{i}$ such that $\sum k_{i}A_{i} $, where $A_{i}$ is $i$th column vector of A. In such ase, $b$ is in the column space of A. $Col(A)$ is a subspace of $R^{m}$.

#### 2-2. The Null Space of A.  

The null space of A, $N(A)=\{x\}$, $\forall{x}$ such that $Ax=0$. $N(A)$ is a subspace of $R^{n}$. 

